
all: conjugate conjugate-mf
	
conjugate: conjugate.cpp
	g++ conjugate.cpp -o conjugate

conjugate-mf: conjugate-mf.cpp
	g++ conjugate-mf.cpp -o conjugate-mf

clean:
	rm -rf conjugate conjugate-mf *.o core
